name: build cdn-proxy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: build app
        run: go build -o cdn-proxy ./main.go

      - name: archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cdn-proxy-app-build
          path: ./cdn-proxy